version: 2.1
orbs:
    node: circleci/node@5.0.2

jobs:
  test-must-passes:

    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      # - run:
      #     name: " npm i "
      #     node-version: "12.22"
      - run:
          name: "node version"
          command: "node --version"
      - run:
          name: "npm version"
          command: "npm --version"
      - run:
          name: "installing packages"
          command: "yarn "
      - run:
          name: "yarn test"
          command: "yarn test a"
      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - test-must-passes